easy_admin:
    site_name: 'YT <em style="font-size: 80%;">series</em>'
    design:
        brand_color: '#232222'
        menu:
          - label: 'Dashboard'
            route: 'admin_dashboard'
            icon: 'tachometer'
            default: true
          - label: 'Series'
            icon: 'shield'
            children:
              - Series
              - Season
              - Episode
          - label: 'Security'
            icon: 'shield'
            children:
              - User
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                  - 'username'
                  - 'email'
                  - 'lastLogin'
                  - { property: 'enabled', label: 'Active' }
            edit:
                fields:
                    - username
                    - email
                    - enabled
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                          multiple: true
                          choices:
                              'ROLE_API': 'ROLE_API'
                              'ROLE_USER': 'ROLE_USER'
                              'ROLE_ADMIN': 'ROLE_ADMIN'
                    - groups
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information', icon: 'info' }
                    - username
                    - email

                    - { type: 'group', css_class: 'col-sm-6', label: 'Password', icon: 'key' }
                    - { property: 'plainPassword', type: 'repeated', type_options: { required: true} }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Security', icon: 'lock' }
                    - enabled
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                          multiple: true
                          choices:
                              'ROLE_API': 'ROLE_API'
                              'ROLE_USER': 'ROLE_USER'
                              'ROLE_ADMIN': 'ROLE_ADMIN'
                    - groups
                form_options: { validation_groups: ['Registration'] }
        Series:
            class: App\Entity\Series
            list:
                fields:
                  - locale
                  - name
                  - seasons
            form:
                fields:
                  - locale
                  - name
                  - image
                  - description
                  - seasons
        Season:
            class: App\Entity\Season
            list:
                fields:
                  - series
                  - rank
                  - name
                  - episodes
            form:
                fields:
                  - series
                  - rank
                  - name
                  - description
                  - episodes
        Episode:
            class: App\Entity\Episode
            list:
                fields:
                  - season
                  - rank
                  - code
                  - name
            form:
                fields:
                  - season
                  - rank
                  - code
                  - name
                  - description
