fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "noreply@tyseries.com"
    sender_name: "tyseries"
  service:
    mailer: fos_user.mailer.twig_swift

services:
  fos_user.listener.flash:
    class: FOS\UserBundle\EventListener\FlashListener
    arguments:
    - 'Symfony\Component\HttpFoundation\Session\Session'
    - 'Symfony\Component\Translation\TranslatorInterface'
