lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl: 3600

gesdinet_jwt_refresh_token:
    ttl: 2592000
    user_identity_field: username
    user_provider: fos_user.user_provider.username
