version: '3'

volumes:
  bdd:

networks:  # Uncomment on linux for static IP and xdebug
  dev:
    driver: bridge
    ipam:
      config:
      - subnet: 10.12.0.0/16  # Ip range for static ip on dev mod

services:
  ngnix:
    build: docker/nginx
    volumes:
    - ./back:/www/
    networks:
      dev:
        ipv4_address: 10.12.0.6 # add this to your host ytseries
      default:

  phpfpm:
    build:
      context: docker/phpfpm
      args:
      - uid=1000
    volumes:
    - ./back:/www/

  postgres:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: passwd
    volumes:
    - bdd:/var/lib/postgresql/data
    networks:
      dev:
        ipv4_address: 10.12.0.7 # ip used for pgAdmin
      default:

  mailcatcher:
    image: tophfr/mailcatcher
    networks:
      dev:
        ipv4_address: 10.12.0.8 # add this to your host ytseriesmail
      default:

  elasticsearch:
    image: elasticsearch:5-alpine

  kibana:
    image: kibana
    networks:
      dev:
        ipv4_address: 10.12.0.9 # go on http://10.12.0.9:5601
      default: