version: '3'

networks:  # Uncomment on linux for static IP and xdebug
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16  # Ip range for static ip on dev mod

services:
  elasticsearch:
    image: elasticsearch:5-alpine
    networks:
      dev:
        ipv4_address: 10.2.0.1
      default:
