#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

api_refresh_token:
  path:     /api/token_refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }