version: '3'

services:
    # DATABASE_URL
    database:
        image: postgres:11.3-alpine
        restart: always
        environment:
            POSTGRES_DB: symfony
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: passwd

    mailcatcher:
        image: tophfr/mailcatcher

    elasticsearch:
        image: elasticsearch:alpine
