version: '3'

volumes:
    bdd:

networks:  # Uncomment on linux for static IP and xdebug
    dev:
        driver: bridge
        ipam:
            config:
                - subnet: 10.109.0.0/16  # Ip range for static ip on dev mod

services:
    database:
        volumes:
            - bdd:/var/lib/postgresql/data
        networks:
            dev:
                ipv4_address: 10.109.0.4
            default:

    mailcatcher:
        networks:
            dev:
                ipv4_address: 10.109.0.5
            default:

    elasticsearch:
        networks:
            dev:
                ipv4_address: 10.109.0.6
            default:
