#!/bin/sh

display()
{
    echo "" && \
    echo "    /  \   _ __ ___  ___    "   && \
    echo "   / /\ \ | '_ \` _ \/ __|  "   && \
    echo "  / ____ \| | | | | \__ \   "   && \
    echo " /_/    \_\_| |_| |_|___/   "$* && \
    echo ""
}

display_success()
{
    echo " \e[42;30m [DONE] $* \e[0m"
}

# disabled hook
exit 0

# check php syntax
display "Checking PSR-2"
./docker.sh phpcs && display_success "PSR-2 Syntax checked"
PHPCS=$?

# check php mess
display "PHP Mess Detector"
./docker.sh phpmd && display_success "PHP Mess Detector"
PHPMD=$?

# check js syntax
display "Checking TsLint"
./front/node_modules/tslint/bin/tslint --project ./front && display_success "Javascript syntax checked"
TSLINT=$?

exit $(( $PHPCS + $PHPMD + $TSLINT ))
